name: Deploy Angular to GitHub Pages

# Se ejecuta cada vez que hagas push a main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Clona tu repositorio
    - name: Checkout
      uses: actions/checkout@v3

    # 2️⃣ Instala Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    # 3️⃣ Instala dependencias de tu proyecto
    - name: Install dependencies
      run: npm install

    # 4️⃣ Construye la app Angular en modo producción
    - name: Build Angular app
      run: npm run build -- --configuration production --output-path=dist/angular-car --base-href "/angular-car/"

    # 5️⃣ Publica en GitHub Pages usando la rama gh-pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/angular-car
